# Generated by Django 4.2.5 on 2023-10-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_rename_students_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='session',
        ),
    ]
