# Generated by Django 4.2.5 on 2023-10-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_remove_student_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='industries',
            field=models.CharField(default='tets', max_length=200),
        ),
    ]
